from fpdf import FPDF

def Generate_PDF(Settings: dict, Configuration: dict, Invoice: dict, Table_Data: list) -> FPDF:
    # ---------------------------- Defaults ----------------------------#
    Invoice_Number = Invoice["invoice"]["invoice_header"]["invoice_info"]["invoice_id"]
    Invoice_Date = Invoice["invoice"]["invoice_header"]["invoice_info"]["invoice_date"] 

    class PDF(FPDF):
        def header(self):
            # Rendering logo:
            self.image(f"Libs\\GUI\\Icons\\Company_Light.png", 10, 8, 33)
            # Setting font: helvetica bold 15
            self.set_font("helvetica", style="B", size=14)
            # Moving cursor to the right:
            self.cell(40)
            # Printing title:
            header_text = f"Invoice: {Invoice_Number}\nInvoice date: {Invoice_Date}"
            self.multi_cell(0, 10, header_text, 0, '')
            self.ln(10)

        def chapter_title(self, num, label):
            # Setting font: helvetica 12
            self.set_font("helvetica", size=10)
            # Setting background color
            self.set_fill_color(200, 220, 255)
            # Printing chapter name:
            self.cell(
                0,
                6,
                f"{label}",
                new_x="LMARGIN",
                new_y="NEXT",
                align="L",
                fill=True,
            )
            # Performing a line break:
            self.ln(4)

        def print_chapter(self, num, title):
            self.chapter_title(num, title)

        def footer(self):
            # Position cursor at 1.5 cm from bottom:
            self.set_y(-15)
            # Setting font: helvetica italic 8
            self.set_font("helvetica", style="I", size=8)
            # Printing page number:
            self.cell(30, 10, "Generated by HQ Testing Tool", border=0, align="L")

    pdf = PDF()
    pdf.add_page()
    pdf.print_chapter(1, "Items Lines")
    pdf.set_font("helvetica", size=10)
    pdf.set_fill_color(0, 0, 0)
    with pdf.table() as table:
        pdf.set_font("helvetica", size=11)
        for data_row in Table_Data:
            row = table.row()
            for datum in data_row:
                row.cell(datum)

    return pdf
